version: '3.1'

services: 
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  nuxt:
    image: node:alpine
    restart: always
    volumes:
      - ./nuxt:/home/node
    tty: true
    working_dir: /home/node
    command: [node, webhook.js]
  
  nginx:
    image: nginx:alpine
    restart: always
    ports: 
      - 8000:80
    volumes: 
      - ./nuxt/dist:/usr/share/nginx/html

volumes:
  wordpress:
  db:
  nuxt: